// Generated by CoffeeScript 1.7.1
(function() {
  var cookieParser, express, mps, request, should;

  request = require("supertest");

  should = require("should");

  express = require("express");

  cookieParser = require("cookie-parser");

  mps = require("../lib/index");

  describe("multi process session test", function() {
    var agent, app;
    app = express();
    app.use(cookieParser());
    app.use(mps());
    app.get("/", function(req, res) {
      return res.send("cookie has set");
    });
    app.get("/set-session", function(req, res) {
      var key, value;
      key = req.query.key;
      value = req.query.value;
      req.session[key] = value;
      return res.send("set session => " + key + " = " + value);
    });
    app.get("/get-session", function(req, res) {
      var key;
      key = req.query.key;
      return res.send(req.session[key]);
    });
    agent = request.agent(app);
    return it("should save cookie", function(done) {
      return agent.get("/").expect(200).expect("set-cookie", /sid=.*/, done);
    });
  });

}).call(this);

//# sourceMappingURL=index.map
