// Generated by CoffeeScript 1.7.1

/*
Created by massimo on 2014/4/14.
 */

(function() {
  var client, redis;

  redis = require("redis");

  client = redis.createClient();


  /*
  设置session
  @param sessionID
  @param session
  @param callback
   */

  exports.setSession = function(sessionID, session, callback) {
    if (!session || Object.getOwnPropertyNames(session).length === 0) {
      return callback(null);
    } else {
      return client.set(sessionID, JSON.stringify(session), function(err) {
        return client.expire(sessionID, 60 * 60 * 24 * 7, function(err) {
          if (typeof callback === "function") {
            return callback(err);
          }
        });
      });
    }
  };


  /*
  获取session值
  @param sessionID
  @param callback
   */

  exports.getSession = function(sessionID, callback) {
    if (callback && typeof callback === "function") {
      return client.get(sessionID, function(err, result) {
        var redisResult;
        if (err) {
          return callback(err);
        } else {
          redisResult = JSON.parse(result) || {};
          return callback(null, redisResult);
        }
      });
    } else {
      throw new Error("need a callback function");
    }
  };


  /*
  删除session
  @param sessionId
   */

  exports.removeSession = function(sessionId) {
    return client.del(sessionId, function(err, result) {
      if (err) {
        return console.dir(err);
      }
    });
  };

}).call(this);

//# sourceMappingURL=redisHelper.map
